// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoadfsfoghgtnunhwbac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvYWRmc2ZvZ2hndG51bmh3YmFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjgwNjcsImV4cCI6MjA2NDAwNDA2N30.m4cN9cOQhuhWnpbj-sQb3EBBSYIZbC_X2r1CsKZdifs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);